export const locomotionStates = Object.freeze({
  ground: "Ground",
  hover: "Hover",
  fall: "Fall",
  jet: "Jet",
});

export const gameConfig = Object.freeze({
  projectName: "3D Robot Air Combat Boss Battle",
  runtimeCanvasId: "runtime-canvas",
  hudRootId: "hud-root",
  mobileControlsRootId: "mobile-controls-root",
  bootOverlayId: "boot-overlay",
  renderer: {
    pixelRatioCap: 2,
    toneMappingExposure: 1.1,
    cameraNear: 0.35,
  },
  arena: {
    size: 680,
    terrainSegments: 220,
    playRadius: 300,
    playerSpawn: Object.freeze([0, 0, 92]),
    bossSpawn: Object.freeze([0, 0, 0]),
  },
  player: {
    hp: 420,
    hoverRelightMinimum: 10,
    hoverMaintainMinimum: 5,
    groundSpeed: 21,
    hoverSpeed: 17,
    fallSpeed: 14,
    hoverVerticalSpeed: 11,
    jetSpeed: 190,
    jetDurationCap: 0.55,
    groundAcceleration: 22,
    airAcceleration: 12.5,
    braking: 17,
    gravity: 24,
    hoverLift: 20,
    hoverDamping: 5.5,
    liftoffImpulse: 5.2,
    ascendImpulse: 9.2,
    contactOffset: 1.05,
    groundMagnetStrength: 24,
    jetDamageMultiplier: 0.45,
    modelScale: 1,
    modelAsset: Object.freeze({
      targetHeight: 5.9,
      rotationY: Math.PI,
      muzzleHeightRatio: 0.57,
      lockHeightRatio: 0.8,
      cameraHeightRatio: 0.74,
      frontInsetRatio: 0.14,
      cameraDepthRatio: 0.6,
      weaponForwardOffsetRatio: 0.055,
      centerJetBlend: 0.32,
      centerJetDropRatio: 0.06,
      centerJetBackRatio: 0.03,
      cameraPort: Object.freeze([0, 3.72, 0.24]),
      lockPort: Object.freeze([0, 3.64, 0.22]),
      anchorOffsets: Object.freeze({
        jetLeft: Object.freeze([0.6, 0.06, 0.13]),
        jetRight: Object.freeze([-0.63, 0.05, 0.13]),
        centerJet: Object.freeze([0, 0.82, 0.06]),
        gunLeft: Object.freeze([2.1, 1.1, -0.7]),
        gunRight: Object.freeze([-2.1, 1.1, -0.7]),
      }),
      jetPorts: Object.freeze({
        left: Object.freeze([4.25, 1.38, 0.18]),
        right: Object.freeze([-4.25, 1.38, 0.18]),
        center: Object.freeze([0, 3.62, 0.96]),
        footLeft: Object.freeze([0.84, 0.24, 0.42]),
        footRight: Object.freeze([-0.84, 0.24, 0.42]),
      }),
      muzzlePorts: Object.freeze({
        left: Object.freeze([3.15, 3.32, -1.32]),
        right: Object.freeze([-3.15, 3.32, -1.32]),
      }),
      barrelTipLocalOffsets: null,
      namedAnchors: Object.freeze({
        nozzleLeft: "DEF-NOZZLE.L_0129",
        nozzleRight: "DEF-NOZZLE.R_0132",
        gunLeft: "DEF-MINIGUN.L_0121",
        gunRight: "DEF-MINIGUN.R_0157",
        cameraBase: "DEF-CAMERAS-BASE_0140",
      }),
    }),
  },
  energy: {
    max: 150,
    groundRegen: 28,
    airRegen: 12,
    groundMoveDrain: 1.8,
    hoverDrain: 8.5,
    jetStartCost: 18,
    jetDrain: 0,
    jetMinimum: 18,
    shootCost: 2,
  },
  boss: {
    hp: 980,
    weakPointDamageMultiplier: 1.5,
    cycleSeconds: 4.6,
    telegraphSeconds: 0.9,
    shockwaveSpeed: 34,
    shockwaveWidth: 4.4,
    shockwaveDamage: 34,
    dodgeHeight: 2.2,
    weakPointRadius: 2.4,
  },
  lockOn: {
    acquireDistance: 520,
    graceSeconds: 0.85,
    hardBreakDistance: 650,
    viewDotThreshold: -0.18,
  },
  combat: {
    shotsPerSecond: 12,
    projectileSpeed: 180,
    projectileLifetime: 1.7,
    projectileDamage: 8,
    projectileRadius: 0.28,
    homingStrength: 3.5,
  },
  camera: {
    sharedDistance: 16.5,
    sharedHeight: 5.1,
    sharedShoulderOffset: 1.9,
    sharedLookLift: 0.72,
    freeDistance: 13,
    freeHeight: 3.8,
    freeShoulderOffset: 1,
    freeAimDistance: 220,
    freeAirDistanceBoost: 2.2,
    freeAirHeightBoost: 1.4,
    freeAirLookLift: 0.45,
    freeAirMaxElevationDegrees: 18,
    freeMinPlanarDistance: 12.6,
    freeMinHeightAboveAnchor: 2.7,
    freePitchMin: -0.35,
    freePitchMax: 0.7,
    freeLookSensitivity: 0.0028,
    mobileLookSensitivity: 0.0054,
    followTurnSpeed: 6.5,
    positionSmoothing: 8,
    targetSmoothing: 12,
    airTrackingBoost: 4.5,
    jetTrackingBoost: 12,
    lockBaseDistance: 20,
    lockDistanceScale: 0.18,
    lockMinDistance: 18,
    lockMaxDistance: 32,
    lockAirDistanceBoost: 3.2,
    lockSideOffset: 2.8,
    lockHeightBase: 6.4,
    lockHeightScale: 0.4,
    lockAirHeightBoost: 2.2,
    lockAirLookLift: 1.1,
    lockAirTargetBias: 0.14,
    lockAirMaxElevationDegrees: 22,
    lockMinPlanarDistance: 12,
    lockMinHeightAboveAnchor: 3.1,
    jetFov: 60,
    fovRecovery: 10,
    orientationBossWeight: 0.75,
    orientationMoveWeight: 0.25,
  },
  ui: {
    reticleMargin: 24,
    hitFlashDuration: 0.22,
  },
});

export default gameConfig;
