export const locomotionStates = Object.freeze({
  ground: "Ground",
  hover: "Hover",
  fall: "Fall",
  jet: "Jet",
});

export const gameConfig = Object.freeze({
  projectName: "3D Robot Air Combat Boss Battle",
  runtimeCanvasId: "runtime-canvas",
  hudRootId: "hud-root",
  mobileControlsRootId: "mobile-controls-root",
  bootOverlayId: "boot-overlay",
  renderer: {
    pixelRatioCap: 2,
    toneMappingExposure: 1.1,
  },
  arena: {
    size: 280,
    terrainSegments: 140,
    playRadius: 132,
    playerSpawn: Object.freeze([0, 0, 34]),
    bossSpawn: Object.freeze([0, 0, 0]),
  },
  player: {
    hp: 240,
    hoverRelightMinimum: 12,
    hoverMaintainMinimum: 6,
    groundSpeed: 15,
    hoverSpeed: 13,
    fallSpeed: 10,
    hoverVerticalSpeed: 9,
    jetSpeed: 28,
    jetDurationCap: 0.38,
    groundAcceleration: 18,
    airAcceleration: 10,
    braking: 16,
    gravity: 24,
    hoverLift: 20,
    hoverDamping: 5.5,
    liftoffImpulse: 4.4,
    ascendImpulse: 7.5,
    contactOffset: 1.05,
    groundMagnetStrength: 24,
    jetDamageMultiplier: 0.45,
    modelScale: 1,
    modelAsset: Object.freeze({
      targetHeight: 4.35,
      rotationY: Math.PI,
      muzzleHeightRatio: 0.57,
      lockHeightRatio: 0.8,
      cameraHeightRatio: 0.74,
      frontInsetRatio: 0.14,
      cameraDepthRatio: 0.6,
    }),
  },
  energy: {
    max: 100,
    groundRegen: 18,
    airRegen: 6,
    groundMoveDrain: 5,
    hoverDrain: 14,
    jetStartCost: 10,
    jetDrain: 36,
    jetMinimum: 24,
    shootCost: 8,
  },
  boss: {
    hp: 400,
    weakPointDamageMultiplier: 1.5,
    cycleSeconds: 4.6,
    telegraphSeconds: 0.9,
    shockwaveSpeed: 34,
    shockwaveWidth: 4.4,
    shockwaveDamage: 34,
    dodgeHeight: 2.2,
    weakPointRadius: 2.4,
  },
  lockOn: {
    acquireDistance: 260,
    graceSeconds: 0.85,
    hardBreakDistance: 320,
    viewDotThreshold: -0.18,
  },
  combat: {
    shotsPerSecond: 4.5,
    projectileSpeed: 72,
    projectileLifetime: 3,
    projectileDamage: 12,
    projectileRadius: 0.4,
    homingStrength: 6,
  },
  camera: {
    freeDistance: 13,
    freeHeight: 3.8,
    freeShoulderOffset: 1,
    freePitchMin: -0.35,
    freePitchMax: 0.7,
    freeLookSensitivity: 0.0028,
    mobileLookSensitivity: 0.0054,
    followTurnSpeed: 6.5,
    positionSmoothing: 8,
    targetSmoothing: 12,
    lockBaseDistance: 20,
    lockDistanceScale: 0.18,
    lockMinDistance: 18,
    lockMaxDistance: 32,
    lockSideOffset: 2.8,
    lockHeightBase: 6.4,
    lockHeightScale: 0.4,
    orientationBossWeight: 0.75,
    orientationMoveWeight: 0.25,
  },
  ui: {
    reticleMargin: 24,
    hitFlashDuration: 0.22,
  },
});

export default gameConfig;
